"""Write the 5 new Sprint 2 check functions into bench.py."""
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[1]
bench_path = REPO / "benchmarks" / "juiceshop" / "bench.py"

NEW_CHEC(
    "\n\n"
    "async def check_xss_reflected(t: Target) -> CheckResult:\n"
    "    probe = chr(60) ipt' + chr(62) + 'alert(1)' + chr(60) + '/script' + chr(62)\n"
    "    r = await t.c.get(f\"{t.base}/rest/products/search\", params={\"q\":"
    "    body = r.text if r.status_code == 200 else \"\"\n"
  "    confirmed = probe in body\n"
    "    return CheckResult(\n"
    "        \"xss_reflected\",\n"
    "        confirmed,\n"
    "   VALIDATED\" if confirmed else \"NOT_FOUND\",\n"
    "        confidence=1.0 if coed else 0.0,\n"
    "        evidence={\"status\": r.sde, \"probe_reflected\": confirmed},\n"
    "    )\n"
    "\n\n"
    "async def check_ftp_directory_listing(t: Target) -> CheckResult:\n"
    "    r = await t.c.get(f\".base}/ftp\")\n"
    "    body = r.text if r.status_code == 200 else \"\"\n"
    "    confirmed = r.status_code == 200 and (\n"
    "        \"acquisitions\" in body.lower() or \".md\" in body.lower() or \".bak\" in body.lower()\n
    "    )\n"
    "    return CheckResult(\n"
    "        \"ftp_directory_listing\",\n"
    "        confirmed,\n"
    "        \"VALIDATED\" if confirmed else \"NOT_FOUND\",\n"
    "        confidence=1.0 if confirmed else 0.0,\n"
    "        evidence={\"status\": r.status_code, \"listing_found\": confirmed},\n"
    "    )\n"
    "\n\n"
    "async def check_unauth_user_list(t: Target) -> ChkResult:\n"
    "    r = await t.c.get(f\"{t.base}/api/Users\")\n"
    "    try:\n"
    "        data = r.json().get(\"data\", [])\n"
    "    except Exception:\n"
    "        data = []\n"
    "    confirmed = r.status_code == 200 and isinstance(data, list) and len(data) > 0\n"
    "    return CheckResult(\n"
    "        \"unauth_user_list\",\n"        confirmed,\n"
    "        \"VALIDATED\" if confirmed else \"NOT_FOUND\",\n"
    "        confidence=1.0 if confirmed else 0.0,\n"
    "        evidence={\"status\": r.status_code, \"user_count\": len(data)},\n"
    "    )\n"
    "\n\n"
    "async def check_weak_password_policy(t: Target) -> CheckResult:\n"
    "    import uuid\n"
    "    email = f\"bench-weak-{uuid.uuid4().hex[:8]}@example.com\"\n"
     body = {\n"
    "        \"email\": email,\n"
    "        \"password\": \"a\",\n"
    "        \"passwordRepeat\": \"a\",\n"
    "        \"securityQuestion\": {\"id\": 1},\n"
    "        \"securityAnswer\": \"bench\",\n"
    "    }\n"
    "    r = await t.c.post(f\"{t.base}/api/Users\", json=body)\n"
    "    confirmed = r.status_code in (200, 201)\n"
    "    return Chlt(\n"
    "        \"weak_password_policy\",\n"
    "        confirmed,\n"
    "        \"VALIDATED\" if confirmed else \"NOT_FOUND\",\n"
    "        confidence=1.0 if confirmed else 0.0,\n"
    "        evidence={\"status\": r.status_code, \"weak_pw_accepted\": confirmed},\n"
    "    )\n"
    "\n\n"
    "async def check_open_redirect(t: Target) -> CheckResult:\n"
    "    import httpx as _httpx\n"
    "    async with _httpx.AsyncClient(timeout=10.0, verify=False, follow_redirects=False) as c:\n"
    "        r = await c.get(f\"{t.base}/redirect\", params={\"to\": \"https://google.com\"})\n"
    "    loc = r.headers.get(\"location\", \"\")\n"
    "    confirmed = r.status_code in (301, 302, 303, 307, 308) and \"google.com\" in loc\n"
    "    return CheckResult(\n"
    "        \"open_redirect\",\n"
    "        confirmed,\n"
    "        \"VALIDATED\" if confirmed else \"NOT_FOUND\",\n"
    "        confidence=1.0 if confirmed else 0.0,\n"
    "        evidence={\"status\": r.status_code, \"location\": loc, \"redirect_confirmed\": confirmed},\n"
    "    )\n"
    "\n\n"
)

content = bench_path.read_text(encoding="utf-8")
MARKER = "CHECKS: dict[str, Callable[[Target], Any]] = {"
if "check_xss_reflected" not in content:
    idx = content.index(MARKER)
    content = content[:idx] + NEW_CHECKS + content[idx:]
    bench_path.write_text(content, encoding="utf-8")
    print("Inserted 5 new check functions OK")
else:
    print("Already present, skipping")
