/** @type {import('tailwindcss').Config} */
// Design tokens ported verbatim from the former cdn.tailwindcss.com inline
// config (the values the UI actually rendered with) so the PostCSS build
// reproduces the same utilities. Consumed by the Tailwind v4 PostCSS plugin
// via `@config "../tailwind.config.js"` in src/styles.css.
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#050505",
        "on-secondary-fixed-variant": "#00531b",
        "inverse-primary": "#006b54",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#00725a",
        "surface-bright": "#3a3939",
        "tertiary-container": "#ffd9d7",
        "on-primary": "#00382b",
        "outline-variant": "#1a1a1a",
        "on-tertiary": "#68000e",
        "primary-fixed-dim": "#00e0b3",
        "on-surface-variant": "#b9cbc2",
        "on-tertiary-fixed": "#410006",
        "on-error": "#690005",
        error: "#ff003c",
        "surface-tint": "#00ffcc",
        "on-primary-fixed-variant": "#00513f",
        "on-background": "#e5e2e1",
        "secondary-container": "#00ff66",
        "on-tertiary-container": "#ca0026",
        "on-secondary": "#003911",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#24ffcd",
        "secondary-fixed-dim": "#00e55b",
        "tertiary-fixed-dim": "#ffb3af",
        primary: "#fdfffc",
        "tertiary-fixed": "#ffdad8",
        "on-surface": "#e5e2e1",
        "primary-container": "#00ffcc",
        "surface-container-highest": "#353534",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#930019",
        "on-primary-fixed": "#002118",
        "secondary-fixed": "#6bff83",
        "surface-container-low": "#1c1b1b",
        surface: "#0a0a0a",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "surface-dim": "#050505",
        "surface-variant": "#1a1a1a",
        secondary: "#ebffe6",
        tertiary: "#fffeff",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#002107",
        outline: "#333333",
        "on-secondary-container": "#007128",
      },
      borderRadius: {
        // Faithful to the prior v3 CDN rendering: design is sharp-cornered.
        none: "0",
        sm: "0.125rem",
        DEFAULT: "0px",
        md: "0.375rem",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "16px",
        unit: "4px",
        margin: "24px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.15em", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
