/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Surfaces
        bg:          "var(--bg-app)",
        "bg-page":   "var(--bg-page)",
        "surface-0": "var(--surface-0)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "surface-4": "var(--surface-4)",
        "surface-hover":    "var(--surface-hover)",
        "surface-active":   "var(--surface-active)",
        "surface-raised":   "var(--surface-raised)",
        "surface-overlay":  "var(--surface-overlay)",

        // Text
        "text-primary":    "var(--text-primary)",
        "text-secondary":  "var(--text-secondary)",
        "text-tertiary":   "var(--text-tertiary)",
        "text-disabled":   "var(--text-disabled)",

        // Accent
        "accent":       "var(--accent)",
        "accent-dim":   "var(--accent-dim)",
        "accent-bg":    "var(--accent-bg)",

        // Interactive
        "interactive":       "var(--interactive)",
        "interactive-dim":   "var(--interactive-dim)",
        "interactive-bg":    "var(--interactive-bg)",

        // Semantic
        "success":     "var(--success)",
        "success-bg":  "var(--success-bg)",
        "warning":     "var(--warning)",
        "warning-bg":  "var(--warning-bg)",
        "danger":      "var(--danger)",
        "danger-bg":   "var(--danger-bg)",
        "info":        "var(--info)",
        "info-bg":     "var(--info-bg)",

        // Borders
        "border-default": "var(--border)",
        "border-subtle":  "var(--border-subtle)",
        "border-strong":  "var(--border-strong)",

        // Legacy aliases (mapped to new tokens for backward compat)
        background:         "var(--bg-app)",
        surface:            "var(--surface-0)",
        "surface-variant":  "var(--surface-2)",
        "surface-container-lowest": "var(--surface-0)",
        "surface-container-low":    "var(--surface-1)",
        "surface-container":        "var(--surface-1)",
        "surface-container-high":   "var(--surface-2)",
        "surface-container-highest":"var(--surface-3)",
        "on-surface":        "var(--text-primary)",
        "on-surface-variant": "var(--text-secondary)",
        primary:             "var(--accent)",
        "primary-fixed":     "var(--accent)",
        "primary-container": "var(--accent-bg)",
        "on-primary":        "var(--accent-on)",
        "on-primary-fixed":  "var(--accent-on)",
        "on-primary-container": "var(--accent)",
        secondary:           "var(--interactive)",
        "secondary-fixed":   "var(--interactive)",
        "secondary-container":"var(--interactive-bg)",
        "on-secondary-container": "var(--interactive)",
        tertiary:            "var(--warning)",
        error:               "var(--danger)",
        "error-container":   "var(--danger-bg)",
        "on-error-container": "var(--danger-on)",
        warning:             "var(--warning)",
        "warning-container": "var(--warning-bg)",
        outline:             "var(--border-strong)",
        "outline-variant":   "var(--border)",
      },
      borderRadius: {
        none: "0",
        xs:   "var(--radius-xs)",
        sm:   "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md:   "var(--radius-md)",
        lg:   "var(--radius-lg)",
        xl:   "var(--radius-xl)",
        "2xl": "16px",
        "3xl": "24px",
        full: "var(--radius-full)",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "var(--sp-4)",
        unit:   "var(--sp-1)",
        0.5: "2px",
        1:   "4px",
        1.5: "6px",
        2:   "8px",
        3:   "12px",
        4:   "16px",
        5:   "20px",
        6:   "24px",
        7:   "28px",
        8:   "32px",
        9:   "36px",
        10:  "40px",
        12:  "48px",
        14:  "56px",
        16:  "64px",
        20:  "80px",
        24:  "96px",
      },
      fontFamily: {
        sans:  ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        mono:  ["JetBrains Mono", "monospace"],
        // Legacy aliases
        "body-md":          ["Inter"],
        "display-lg":       ["Inter"],
        "headline-md":      ["Inter"],
        "label-caps":       ["JetBrains Mono"],
        "code-sm":          ["JetBrains Mono"],
      },
      fontSize: {
        "xs":   ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "sm":   ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "md":   ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "lg":   ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "xl":   ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "2xl":  ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "3xl":  ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
        "label-xs":   ["10px", { lineHeight: "13px", letterSpacing: "0.08em", fontWeight: "700" }],
        "code-sm":    ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        "sm":    "var(--shadow-sm)",
        "md":    "var(--shadow-md)",
        "lg":    "var(--shadow-lg)",
        "glow":  "var(--shadow-glow)",
        "glow-cyan": "var(--shadow-glow-cyan)",
        "glow-red":  "var(--shadow-glow-red)",
        "none":  "none",
      },
      transitionDuration: {
        "fast":   "var(--duration-fast)",
        "normal": "var(--duration-normal)",
        "slow":   "var(--duration-slow)",
      },
      transitionTimingFunction: {
        "out":    "var(--ease-out)",
        "in":     "var(--ease-in)",
        "spring": "var(--ease-spring)",
      },
    },
  },
  plugins: [],
}
